### ISSUE TITLE
About HIPIE make.sh

### ISSUE THREAD

**Issue by jifeng35** [berkeley-hipie/segllm#1]
Hello, there! I am interested in your awesome work. Thus, I'm trying to build the environment by following the **_installment.md_**. I came across a problem.Here is the log.
_user@server:my/path/to/segllm/uninext-segm/projects/HIPIE/hipie/models/deformable_detr/ops$ bash make.sh_ 
```
running build
running build_py
copying functions/ms_deform_attn_func.py -> build/lib.linux-x86_64-cpython-310/functions
copying functions/__init__.py -> build/lib.linux-x86_64-cpython-310/functions
copying modules/ms_deform_attn.py -> build/lib.linux-x86_64-cpython-310/modules
copying modules/__init__.py -> build/lib.linux-x86_64-cpython-310/modules
running build_ext
building 'MultiScaleDeformableAttention' extension
Emitting ninja build file /raid_sdd/lwh/algorithm/segllm/uninext-segm/projects/HIPIE/hipie/models/deformable_detr/ops/build/temp.linux-x86_64-cpython-310/build.ninja...
Traceback (most recent call last):
  File "/raid_sdd/lwh/algorithm/segllm/uninext-segm/projects/HIPIE/hipie/models/deformable_detr/ops/setup.py", line 62, in <module>
    setup(
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
    return run_commands(dist)
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
    dist.run_commands()
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/setuptools/dist.py", line 995, in run_command
    super().run_command(command)
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/setuptools/dist.py", line 995, in run_command
    super().run_command(command)
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 99, in run
    _build_ext.run(self)
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 868, in build_extensions
    build_ext.build_extensions(self)
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
    self._build_extensions_serial()
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
    self.build_extension(ext)
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 264, in build_extension
    _build_ext.build_extension(self, ext)
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
    objects = self.compiler.compile(
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 681, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1770, in _write_ninja_file_and_compile_objects
    _write_ninja_file(
  File "/raid_sdd/lwh/mambaforge/envs/segllm/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2300, in _write_ninja_file
    assert len(sources) > 0
AssertionError
```
After running the **bash make.sh** in **segllm/uninext-segm/projects/HIPIE/hipie/models/deformable_detr/ops** work directory, the program told me there is no sources. I also opened the setup.py to see the detail and there seems no *.cpp or *.cu in this work dir.
Look forward to your reply!🧐

**Comment by jifeng35** [comment]
https://github.com/berkeley-hipie/HIPIE/tree/main/projects/HIPIE/hipie/models/deformable_detr/ops
Opsss!You maybe forgot to add the ./src into this project!

**Comment by marlo-z** [comment]
Hi, good catch! Sorry about this. The src folder has been added. Thank you for bringing this issue to our attention!
